/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package arbol.vista;

import javax.swing.JOptionPane;
import arbol.modelo.arbolBinario;
import arbol.modelo.nodoArbol;

public class inicioArbol extends javax.swing.JFrame {
    arbolBinario arbolMain = new arbolBinario();
    /**
     * Creates new form inicioArbol
     */
    public inicioArbol() {
        initComponents();
        setTitle("Arboles");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        porTamaño = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        inOrderLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        preOrderlabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        postOrderLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        padre = new javax.swing.JLabel();
        abuelo = new javax.swing.JLabel();
        tio = new javax.swing.JLabel();
        hermano = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        ingresaNodos = new javax.swing.JButton();
        info1 = new javax.swing.JButton();
        info2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel1.setText("Crear arbol");

        porTamaño.setText("Por tamaño");
        porTamaño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                porTamañoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel2.setText("Info Arbol ");

        jButton1.setText("Consultar nodo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("In order :");

        jLabel5.setText("Pre order");

        jLabel7.setText("Post order");

        jLabel4.setText("Padre");

        jLabel6.setText("Abuelo");

        jLabel8.setText("Tio");

        jLabel9.setText("Hermano");

        jButton2.setText("?");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)
                        .addGap(11, 11, 11)
                        .addComponent(preOrderlabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inOrderLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(postOrderLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(padre)
                        .addGap(56, 56, 56)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(hermano))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(abuelo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(tio)))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(inOrderLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(preOrderlabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(postOrderLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel9)
                    .addComponent(padre)
                    .addComponent(hermano))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(abuelo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tio))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        ingresaNodos.setText("Ingresar nodos");
        ingresaNodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresaNodosActionPerformed(evt);
            }
        });

        info1.setText("?");
        info1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                info1ActionPerformed(evt);
            }
        });

        info2.setText("?");
        info2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                info2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(porTamaño, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ingresaNodos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(info1)
                            .addComponent(info2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(91, 91, 91)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(porTamaño)
                    .addComponent(info1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ingresaNodos)
                    .addComponent(info2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public void limpiarLabel(){
        preOrderlabel.setText("");
        postOrderLabel.setText("");
        inOrderLabel.setText("");
        padre.setText("");
        tio.setText("");
        abuelo.setText("");
        hermano.setText("");
        arbolMain.setInorden("");
        arbolMain.setPosorden("");
        arbolMain.setPreorden("");
    }
    private void info1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_info1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane,"Ingresa la altura del arbol que quieres contruir\npara fines de optimizacion el limite para este\nserá de 25 de altura.");
    }//GEN-LAST:event_info1ActionPerformed

    private void info2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_info2ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane, "Ingresa los nombres de los nodos de tu arbol \n"
                                              + "separados por comas y se creará un arbol aleatorio\ncon estas.");
    }//GEN-LAST:event_info2ActionPerformed

    private void porTamañoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_porTamañoActionPerformed
        // TODO add your handling code here:
        limpiarLabel();
        int tamaño=0;
        try{
            tamaño = Integer.valueOf(JOptionPane.showInputDialog("Ingrese el tamaño"));
            if(tamaño>25){
            JOptionPane.showMessageDialog(rootPane,"Recuerda que el tamaño maximo es 25");
            }
            else{
                arbolMain.aleatorioPorTamaño(tamaño);
                arbolMain.recInorden(arbolMain.getRaiz());
                arbolMain.recPosOrden(arbolMain.getRaiz());
                arbolMain.recPreOrden(arbolMain.getRaiz());
                
                inOrderLabel.setText(arbolMain.getInorden().substring(4));
                postOrderLabel.setText(arbolMain.getPosorden().substring(4));
                preOrderlabel.setText(arbolMain.getPreorden().substring(4));
                
            }
        }catch(NumberFormatException exception){
            JOptionPane.showMessageDialog(rootPane, "Recuerda solo ingresar Numeros");
        }
    }//GEN-LAST:event_porTamañoActionPerformed

    private void ingresaNodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresaNodosActionPerformed
        // TODO add your handling code here:
        
        String nodos =JOptionPane.showInputDialog("Ingresa cada nodo separado por comas");
        limpiarLabel();
        arbolMain.aleatorioDatos(nodos);
        
        arbolMain.recInorden(arbolMain.getRaiz());
        arbolMain.recPosOrden(arbolMain.getRaiz());
        arbolMain.recPreOrden(arbolMain.getRaiz());

        inOrderLabel.setText(arbolMain.getInorden().substring(4));
        postOrderLabel.setText(arbolMain.getPosorden().substring(4));
        preOrderlabel.setText(arbolMain.getPreorden().substring(4));
  
    }//GEN-LAST:event_ingresaNodosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        String dato=JOptionPane.showInputDialog("Ingrese el nodo del que desea informacion");
        padre.setText(arbolMain.elPadre(arbolMain.getRaiz(), dato));
        abuelo.setText(arbolMain.abuelo(arbolMain.getRaiz(), dato));
        tio.setText(arbolMain.tio(arbolMain.getRaiz(), dato));
        hermano.setText(arbolMain.tio(arbolMain.getRaiz(), dato));

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane,"Busca la informacion del nodo que ingreses\nSi el nodo esta en mayuscula debes ingresarlo en mayuscula");
    }//GEN-LAST:event_jButton2ActionPerformed

     

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel abuelo;
    private javax.swing.JLabel hermano;
    private javax.swing.JLabel inOrderLabel;
    private javax.swing.JButton info1;
    private javax.swing.JButton info2;
    private javax.swing.JButton ingresaNodos;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel padre;
    private javax.swing.JButton porTamaño;
    private javax.swing.JLabel postOrderLabel;
    private javax.swing.JLabel preOrderlabel;
    private javax.swing.JLabel tio;
    // End of variables declaration//GEN-END:variables
}
